import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  topicsSidebar: [
    "intro",
    "progress",
    {
      type: "autogenerated",
      dirName: "topics",
    },
  ],
};

export default sidebars;
